### ISSUE TITLE
Feature: NonBlocking Event loop for subscriptions 

### ISSUE THREAD

**Issue by mr-engin3er** [coredumplabs/thingsboard-micropython#1]
Hi, 
I tried this repo and found it requires some features like a nonblocking event loop for subscriptions so we can always get updated data. I used wait_msg() but it only worked one time. 
I think we can use asyncio for this.
If you guide I can contribute.

**Comment by manuargue** [comment]
Hi, `wait_msg()` will block until a message is available, process it and then return. If you need a non-blocking call you can use `check_msg()`, which will behave the same but will return immediately if no message is available. Both methods are just wrappers around the umqtt.simple2 API, you can find more details in [the umqtt.simple2 API reference](https://github.com/fizista/micropython-umqtt.simple2/blob/master/README.rst#api-reference) (umqtt.robust2, the actual library used on this project, has same API as umqtt.simple2). To continue processing messages, you should invoke any of these methods from inside a loop.

asyncio could be an option, but to be honest I wanted to keep this as simple as possible because I did this library with Python beginners in mind. That said, please feel free to fork this project and make the async version :smiley:
I guess the first step would be to replace umqtt.simple2 for one of the MQTT async libraries for MicroPython. Here there are a few I found: https://github.com/tve/mqboard, https://github.com/chrismoorhouse/micropython-mqtt.

**Comment by mr-engin3er** [comment]
Thanks for your response.
I'll try to add a non-blocking event loop.
